<?php

// General Settings
//----------------------------------------------------------------------------------------------------------------------
/**
 * Host with port
 * @description The host and port where the stable diffusion API is running.
 *
 * @var bool
 */
$this->host = 'http://127.0.0.1:7860';

/**
 * Number of images to create
 *
 * @description The number of images to generate. If set to null, the script will generate unlimited images.
 *
 * @var int|null
 */
$this->numberOfImages = 10;

/**
 * Wait for callback from stable diffusion and save images or only call the API to create the images
 *
 * @description If true, the script will wait for the callback from the stable diffusion API and save the images.
 *              If false, the script will only call the API to create the images.
 *
 * @var bool
 */
$this->saveImages = true;

/**
 * Dry run
 *
 * @description If true, only settings will be checked and no images will be created.
 *
 * @var bool
 */
$this->dryRun = false;
//----------------------------------------------------------------------------------------------------------------------



// Stable Diffusion default settings
//----------------------------------------------------------------------------------------------------------------------
/**
 * Model
 *
 * @description String of the model name, array from multiple models, false for selected model, null for all models are
 *              used in turn.
 *
 * @var string|array|false|null
 */
$this->model = null;

/**
 * Mode
 *
 * @description The mode to use. Can be txt2img or img2img. If img2img is selected, the Stable Diffusion img2img
 *              settings has to set correctly and the init images directory has to be set.
 *
 * @var string
 */
$this->mode = 'txt2img';

/**
 * String of prompt generator directory to merge prompt or set null to random select prompt directory
 *
 * @description The directory where the prompt generator files are located. A subdirectory in prompt directory where
 *              prompt files for prompt merging are located. If set to null, the images will be generated by random
 *              prompts directory.
 *
 * @var string|null
 */
$this->prompt = null;

/**
 * Image width
 *
 * @description The width of the generated images.
 *
 * @var int
 */
$this->width = 512;

/**
 * Image height
 *
 * @description The height of the generated images.
 *
 * @var int
 */
$this->height = 512;

/**
 * Number ob sampling steps
 *
 * @description The number of sampling steps to use for the generation.
 *
 * @var int
 */
$this->steps = 20;
//----------------------------------------------------------------------------------------------------------------------



// Stable Diffusion img2img settings
//----------------------------------------------------------------------------------------------------------------------
/**
 * String of img2img init image directory or set null to random select init image directory
 *
 * @description The directory where the images to be initialized are located. A subdirectory in init_images directory
 *              where initialize images are stored.
 *
 * @var string|null
 */
$this->initImages = null;
//----------------------------------------------------------------------------------------------------------------------