<?php

/**
 * Stable Diffusion Image Generator
 *
 * @author      Moses Rivera
 * @copyright   xtrose® Media Studio 2025
 * @license     GNU GENERAL PUBLIC LICENSE
 */

declare(strict_types = 1);



// General Settings
//----------------------------------------------------------------------------------------------------------------------
/**
 * Host with port
 *
 * @description The host and port where the stable diffusion API is running.
 *
 * @var string
 */
$this->host = 'http://127.0.0.1:7860';

/**
 * Start Web-Application
 *
 * @description Start PHP Build-In server for the Web-Application.
 *
 * @var bool
 */
$this->startWebApplication = true;

/**
 * Number of images to create
 *
 * @description The number of images to generate. If set to null or 0, the script will generate unlimited images.
 *
 * @var int|null
 */
$this->numberOfImages = 10;

/**
 * Loop txt2txt -> img2img or loop img2img -> img2img
 *
 * @description Creates a txt2txt -> img2img or img2img -> img2img loop, depending on the mode option. Creates the first
 *              image with the configured mode and all subsequent images as img2img with the generated image.
 * @warning     Will automatically enable saveImages if enabled.
 *
 * @var bool
 */
$this->loop = false;

/**
 * Dry run
 *
 * @description If true, only settings will be checked and no images will be created.
 *
 * @var bool
 */
$this->dryRun = false;
//----------------------------------------------------------------------------------------------------------------------



// Stable Diffusion default settings
//----------------------------------------------------------------------------------------------------------------------
/**
 * Mode
 *
 * @description The mode to use. Can be txt2img or img2img. If img2img is selected, the Stable Diffusion img2img
 *              settings has to set correctly and the init images directory has to be set.
 *
 * @var string
 */
$this->mode = 'txt2img';

/**
 * Checkpoint
 *
 * @description String of the checkpoint name, array from multiple checkpoints, null for all checkpoints are used in
 *              turn, false for selected checkpoint.
 *
 * @var string|array|false|null
 */
$this->checkpoint = null;

/**
 * Sampler
 *
 * @description String of the sampler name, array from multiple samplers, null for all samplers are used in turn, false
 *              for default sampler (Euler).
 *
 * @var string|array|false|null
 */
$this->sampler = false;

/**
 * String of prompt generator directory to merge prompt or set null to random select prompt directory
 *
 * @description The directory where the prompt generator files are located. A subdirectory in prompt directory where
 *              prompt files for prompt merging are located. If set to null, the images will be generated by random
 *              prompts directory.
 *
 * @var string|null
 */
$this->prompt = 'test';

/**
 * String of img2img init image directory or set null to random select init image directory
 *
 * @description The directory where the images to be initialized are located. A subdirectory in init_images directory
 *              where initialize images are stored. Only available if mode is img2img.
 *
 * @var string|null
 */
$this->initImages = 'test';

/**
 * Image width
 *
 * @description The width of the generated images.
 *
 * @var int
 */
$this->width = 512;

/**
 * Image height
 *
 * @description The height of the generated images.
 *
 * @var int
 */
$this->height = 512;

/**
 * Number ob sampling steps
 *
 * @description The number of sampling steps to use for the generation.
 *
 * @var int
 */
$this->steps = 20;

/**
 * Refiner checkpoint
 *
 * @description String of the refiner checkpoint name, array from multiple refiner checkpoints, null for all checkpoints
 *              are used in turn, false for deactivate refiner checkpoint.
 *
 * @var string|array|false|null
 */
$this->refinerCheckpoint = false;

/**
 * Refiner switch at
 *
 * @description Float 0.0 - 1.0 when checkpoint switch to refiner checkpoint. Set 0.5 to set checkpoint should switch to
 *              refiner checkpoint at 50% of image creation.
 *
 * @var float
 */
$this->refinerSwitchAt = 0.8;

/**
 * Restore faces
 *
 * @description Option restore faces and remove artifacts.
 *
 * @var bool
 */
$this->restoreFaces = false;

/**
 * Tiling
 *
 * @description Tiling to generate seamless textures.
 *
 * @var bool
 */
$this->tiling = false;
//----------------------------------------------------------------------------------------------------------------------



// Hires fix (Only txt2img)
//----------------------------------------------------------------------------------------------------------------------
/**
 * Enable hires fix
 *
 * @description Enable or disable hires fix. Only available in txt2img mode.
 *
 * @var bool
 */
$this->enableHr = false;

/**
 * Hr upscaler
 *
 * @description Upscaler type string for specified upscaler, null for default upscaler (Latent). Only available if hires
 *              fix is enabled.
 *
 * @var string|null
 */
$this->hrUpscaler = null;

/**
 * Hr resize width
 *
 * @description Width of the resized image. Only available if hires fix is enabled and hr scale is null.
 *
 * @var int|null
 */
$this->hrResizeX = null;

/**
 * Hr resize height
 *
 * @description Height of the resized image. Only available if hires fix is enabled and hr scale is null.
 *
 * @var int|null
 */
$this->hrResizeY = null;

/**
 * Hr scale
 *
 * @description Scale of the resized image. Only available if hires fix is enabled. Overrides hr resize width and
 *              height if not null.
 *
 * @var float|null
 */
$this->hrScale = 2;

/**
 * Hr sampler
 *
 * @description Sampler type for hires. Only available if hires fix is enabled. Default sampler if null (Euler).
 *
 * @var string|null
 */
$this->hrSamplerName = null;
//----------------------------------------------------------------------------------------------------------------------



// Lora
//----------------------------------------------------------------------------------------------------------------------
/**
 * Sampler
 *
 * @description String of the lora name, array from multiple loras, null for all loras are used in turn, false
 *              for disable lora
 *
 * @var string|array|false|null
 */
$this->lora = false;
//----------------------------------------------------------------------------------------------------------------------